### PR TITLE
Fix home layout

### LINKED ISSUE #2: Fix mobile UI
Grid is broken.

This project is using the [Vuetify](https://vuetifyjs.com/).

| Home | List |
|---|---|
| image | image |

- [ ] Home
- [ ] List

### PR DESCRIPTION
**Pull request by Deeadline**
Fix #2 Home layout

### CODE REVIEW

**Comment by Deeadline** [comment]
@magnobiet Could you check this PR ? ;)

**Comment by Deeadline** [comment]
obraz
On desktop screen

obraz
This is on the mobile screen.

Second issue on mobile screen:
obraz

**Comment by magnobiet** [comment]
Thank you so much @Deeadline.

**Comment by Deeadline** [comment]
No problem ;) If I will have more time, I can get your another issue ;)

**Comment by magnobiet** [comment]
Sure, I appreciate your contributions.

**Pull request merged**
